# This is a basic workflow to help you get started with Actions

name: Build Game

env:
  GODOT_BIN: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
  GODOT_TEMPLATES: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
  ITCHIO_GAME: the-lone-fox
  ITCHIO_USERNAME: dunklecat

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        
      - name: install wine
        id: wine_install
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: godot export release
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: ${{ env.GODOT_BIN }}
          godot_export_templates_download_url: ${{ env.GODOT_TEMPLATES }}
          relative_project_path: ./
          archive_output: true
          export_debug: false
          use_godot_3: true
          export_as_pack: false
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
          
      - name: create release for github
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          # bodyFile: "release.md"
      
      - name: release all versions on itch.io
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          action: "push"
          install_dir: ~/.butler
          butler_version: "latest"
          check_signature: false
          update_path: false
          butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
          itch_game: ${{ env.ITCHIO_GAME }}
          itch_user: ${{ env.ITCHIO_USERNAME }}
          version: ${{ github.ref_name }}
          auto_channel: true
          files: |
            ${{ steps.export.outputs.build_directory }}/Windows/*
            ${{ steps.export.outputs.build_directory }}/Linux/*
            ${{ steps.export.outputs.archive_directory }}/HTML5.zip
          
      
    
