# This is a basic workflow to help you get started with Actions

name: CI

env:
  GODOT_BIN: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
  GODOT_TEMPLATES: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
  ITCHIO_NAME: the-lone-fox
  ITCHIO_USERNAME: dunklecat

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Godot Export Release
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: ${{ GODOT_BIN }}
          godot_export_templates_download_url: ${{ GODOT_TEMPLATES }}
          relative_project_path: ./
          archive_output: true
          export_debug: false
          use_godot_3: true
          export_as_pack: false
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
          
      - name: create release for github
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          # bodyFile: "release.md"
      
      - name: release windows version on itch.io
        uses: yeslayla/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ ITCHIO_GAME }}
          ITCH_USER: ${{ ITCHIO_USERNAME }}
          PACKAGE: ${{ steps.export.outputs.build_directory }}/build/${{ ITCHIO_GAME }}-windows.exe
          VERSION: ${{ github.ref_name }}
          
      - name: release linux version on itch.io
        uses: yeslayla/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ ITCHIO_GAME }}
          ITCH_USER: ${{ ITCHIO_USERNAME }}
          PACKAGE: ${{ steps.export.outputs.build_directory }}/build/${{ ITCHIO_GAME }}-linux.x86_64
          VERSION: ${{ github.ref_name }}
          
      # - name: release html5 version on itch.io
      #   uses: yeslayla/butler-publish-itchio-action@v1.0.2
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: linux
      #     ITCH_GAME: ${{ ITCHIO_GAME }}
      #     ITCH_USER: ${{ ITCHIO_USERNAME }}
      #     PACKAGE: ${{ steps.export.outputs.archive_directory }}/build/html5.zip
          
      
    
